SHEEP:
  LEVELS: 3
  ROTTENFLESH: 40
  BONES: 20
  SHULKERSHELL: 0
  PHANTOMMEMBRANE: 0
  ENABLED: 'true'
COW:
  LEVELS: 3
  ROTTENFLESH: 40
  BONES: 20
  SHULKERSHELL: 0
  PHANTOMMEMBRANE: 0
  ENABLED: 'true'
WOLF:
  LEVELS: 3
  ROTTENFLESH: 24
  BONES: 12
  SHULKERSHELL: 0
  PHANTOMMEMBRANE: 0
  ENABLED: 'true'
PIG:
  LEVELS: 3
  ROTTENFLESH: 40
  BONES: 20
  SHULKERSHELL: 0
  PHANTOMMEMBRANE: 0
  ENABLED: 'true'
RABBIT:
  LEVELS: 3
  ROTTENFLESH: 24
  BONES: 12
  SHULKERSHELL: 0
  PHANTOMMEMBRANE: 0
  ENABLED: 'true'
CHICKEN:
  LEVELS: 3
  ROTTENFLESH: 24
  BONES: 12
  SHULKERSHELL: 0
  PHANTOMMEMBRANE: 0
  ENABLED: 'true'
TURTLE:
  LEVELS: 10
  ROTTENFLESH: 40
  BONES: 20
  SHULKERSHELL: 1
  PHANTOMMEMBRANE: 0
  ENABLED: 'true'
PARROT:
  LEVELS: 3
  ROTTENFLESH: 24
  BONES: 12
  SHULKERSHELL: 0
  PHANTOMMEMBRANE: 0
  ENABLED: 'true'
OCELOT:
  LEVELS: 3
  ROTTENFLESH: 24
  BONES: 12
  SHULKERSHELL: 0
  PHANTOMMEMBRANE: 0
  ENABLED: 'true'
MUSHROOM_COW:
  LEVELS: 3
  ROTTENFLESH: 40
  BONES: 20
  SHULKERSHELL: 0
  PHANTOMMEMBRANE: 0
  ENABLED: 'true'
HORSE:
  LEVELS: 3
  ROTTENFLESH: 40
  BONES: 20
  SHULKERSHELL: 0
  PHANTOMMEMBRANE: 0
  ENABLED: 'true'
ZOMBIE_VILLAGER:
  LEVELS: 3
  ROTTENFLESH: 40
  BONES: 20
  SHULKERSHELL: 0
  PHANTOMMEMBRANE: 0
  ENABLED: 'true'
POLAR_BEAR:
  LEVELS: 3
  ROTTENFLESH: 40
  BONES: 20
  SHULKERSHELL: 0
  PHANTOMMEMBRANE: 0
  ENABLED: 'true'
SLIME:
  LEVELS: 3
  ROTTENFLESH: 0
  BONES: 0
  SHULKERSHELL: 0
  PHANTOMMEMBRANE: 0
  ENABLED: 'true'
PHANTOM:
  LEVELS: 5
  ROTTENFLESH: 24
  BONES: 12
  SHULKERSHELL: 0
  PHANTOMMEMBRANE: 0
  ENABLED: 'true'
WITHER_SKELETON:
  LEVELS: 10
  ROTTENFLESH: 0
  BONES: 30
  SHULKERSHELL: 0
  PHANTOMMEMBRANE: 0
  ENABLED: 'true'
ENDERMITE:
  LEVELS: 3
  ROTTENFLESH: 0
  BONES: 3
  SHULKERSHELL: 0
  PHANTOMMEMBRANE: 0
  ENABLED: 'true'
SHULKER:
  LEVELS: 30
  ROTTENFLESH: 0
  BONES: 0
  SHULKERSHELL: 0
  PHANTOMMEMBRANE: 5
  ENABLED: 'true'

insufficientLEVELS: 'You lack sufficient understanding to perform this ritual.'
